//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name Nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Contacto", ReplyAction="*")]
        WebApplication1.ServiceReference2.ContactoResponse Contacto(WebApplication1.ServiceReference2.ContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Contacto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference2.ContactoResponse> ContactoAsync(WebApplication1.ServiceReference2.ContactoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContactoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Contacto", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference2.ContactoRequestBody Body;
        
        public ContactoRequest() {
        }
        
        public ContactoRequest(WebApplication1.ServiceReference2.ContactoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Mensaje;
        
        public ContactoRequestBody() {
        }
        
        public ContactoRequestBody(string Nombre, string Email, long Telefono, string Asunto, string Mensaje) {
            this.Nombre = Nombre;
            this.Email = Email;
            this.Telefono = Telefono;
            this.Asunto = Asunto;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContactoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ContactoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference2.ContactoResponseBody Body;
        
        public ContactoResponse() {
        }
        
        public ContactoResponse(WebApplication1.ServiceReference2.ContactoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ContactoResult;
        
        public ContactoResponseBody() {
        }
        
        public ContactoResponseBody(string ContactoResult) {
            this.ContactoResult = ContactoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication1.ServiceReference2.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference2.WebService1Soap>, WebApplication1.ServiceReference2.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference2.ContactoResponse WebApplication1.ServiceReference2.WebService1Soap.Contacto(WebApplication1.ServiceReference2.ContactoRequest request) {
            return base.Channel.Contacto(request);
        }
        
        public string Contacto(string Nombre, string Email, long Telefono, string Asunto, string Mensaje) {
            WebApplication1.ServiceReference2.ContactoRequest inValue = new WebApplication1.ServiceReference2.ContactoRequest();
            inValue.Body = new WebApplication1.ServiceReference2.ContactoRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Email = Email;
            inValue.Body.Telefono = Telefono;
            inValue.Body.Asunto = Asunto;
            inValue.Body.Mensaje = Mensaje;
            WebApplication1.ServiceReference2.ContactoResponse retVal = ((WebApplication1.ServiceReference2.WebService1Soap)(this)).Contacto(inValue);
            return retVal.Body.ContactoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference2.ContactoResponse> WebApplication1.ServiceReference2.WebService1Soap.ContactoAsync(WebApplication1.ServiceReference2.ContactoRequest request) {
            return base.Channel.ContactoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference2.ContactoResponse> ContactoAsync(string Nombre, string Email, long Telefono, string Asunto, string Mensaje) {
            WebApplication1.ServiceReference2.ContactoRequest inValue = new WebApplication1.ServiceReference2.ContactoRequest();
            inValue.Body = new WebApplication1.ServiceReference2.ContactoRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Email = Email;
            inValue.Body.Telefono = Telefono;
            inValue.Body.Asunto = Asunto;
            inValue.Body.Mensaje = Mensaje;
            return ((WebApplication1.ServiceReference2.WebService1Soap)(this)).ContactoAsync(inValue);
        }
    }
}
